'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.296
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FoxTools.Shooter.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Внимание.
        '''</summary>
        Friend Shared ReadOnly Property Attention() As String
            Get
                Return ResourceManager.GetString("Attention", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Отмена.
        '''</summary>
        Friend Shared ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Отмена (через {0} сек.).
        '''</summary>
        Friend Shared ReadOnly Property CancelIn() As String
            Get
                Return ResourceManager.GetString("CancelIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Снимок.png.
        '''</summary>
        Friend Shared ReadOnly Property DefaultFileName() As String
            Get
                Return ResourceManager.GetString("DefaultFileName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Ошибка.
        '''</summary>
        Friend Shared ReadOnly Property ErrorTitle() As String
            Get
                Return ResourceManager.GetString("ErrorTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Не удалось отправить изображение на хитрый сервер. Причина: {0}.
        '''</summary>
        Friend Shared ReadOnly Property FoxToolsError() As String
            Get
                Return ResourceManager.GetString("FoxToolsError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Снимок не сделан!.
        '''</summary>
        Friend Shared ReadOnly Property HaveNotScreen() As String
            Get
                Return ResourceManager.GetString("HaveNotScreen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на &lt;&lt; Меньше.
        '''</summary>
        Friend Shared ReadOnly Property Less() As String
            Get
                Return ResourceManager.GetString("Less", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Больше &gt;&gt;.
        '''</summary>
        Friend Shared ReadOnly Property More() As String
            Get
                Return ResourceManager.GetString("More", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Пикселизация {0}px.
        '''</summary>
        Friend Shared ReadOnly Property PixelateValue() As String
            Get
                Return ResourceManager.GetString("PixelateValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Хитрый снимок.png.
        '''</summary>
        Friend Shared ReadOnly Property ScreenFileName() As String
            Get
                Return ResourceManager.GetString("ScreenFileName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Хитрый снимок {0}.png.
        '''</summary>
        Friend Shared ReadOnly Property ScreenFileName2() As String
            Get
                Return ResourceManager.GetString("ScreenFileName2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Не удалось отправить изображение на сервер ZzWeb. Причина: {0}.
        '''</summary>
        Friend Shared ReadOnly Property ZzWebError() As String
            Get
                Return ResourceManager.GetString("ZzWebError", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
