'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.296
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FoxTools.Shooter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property border10px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border10px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property border1px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border1px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property border3px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border3px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property border5px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border5px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copy24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cur_eraser() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("cur_eraser", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property cur_marker() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("cur_marker", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property cur_marker16px() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cur_marker16px", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property cur_pen() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("cur_pen", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property cur_pen16px() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cur_pen16px", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property eraser24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eraser24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property facebook40px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("facebook40px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property foxshooter() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("foxshooter", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property FoxToolsScreenShooter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FoxToolsScreenShooter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gplus40px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gplus40px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mailru40px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mailru40px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property marker24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marker24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ok40px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok40px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property palette50px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("palette50px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pen24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pen24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pixelize24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pixelize24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property progress64px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("progress64px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settings24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shape24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shape24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property share24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("share24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shareft24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shareft24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sharezz24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sharezz24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shooter24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shooter24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property twitter40px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twitter40px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vk40px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vk40px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
